// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SayHello.Web.Database;

namespace SayHello.Web.Migrations
{
    [DbContext(typeof(SayHelloDatabaseContext))]
    [Migration("20190907024953_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SayHello.Web.Database.Hello", b =>
                {
                    b.Property<string>("ISO639LanguageId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HelloText");

                    b.Property<string>("LanguageName");

                    b.HasKey("ISO639LanguageId");

                    b.ToTable("Hellos");
                });
#pragma warning restore 612, 618
        }
    }
}
